<a href="https://colab.research.google.com/github/Sakhiur2022/QSAR-modeling-for-DHFR-TS/blob/main/Descriptor_Dataset_Preparation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Descriptor Calculation and Dataset Preparation**

Sakhiur Rahman

In this notebook, I will be calculating molecular descriptors that are essentially quantitative description of the compounds in the dataset. Finally, I will be preparing this into a dataset for subsequent model building.

---

## **Download PaDEL-Descriptor**

### **New version**

In [1]:
! pip install padelpy

Collecting padelpy
  Downloading padelpy-0.1.16-py3-none-any.whl.metadata (7.7 kB)
Downloading padelpy-0.1.16-py3-none-any.whl (20.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.9/20.9 MB 56.6 MB/s eta 0:00:00
Installing collected packages: padelpy
Successfully installed padelpy-0.1.16

## **Load bioactivity data**

In [2]:
! wget https://github.com/Sakhiur2022/QSAR-modeling-for-DHFR-TS/raw/refs/heads/main/data/preprocessed/bioactivity_preprocessed_data.csv

--2026-06-12 18:00:48--  https://github.com/Sakhiur2022/QSAR-modeling-for-DHFR-TS/raw/refs/heads/main/data/preprocessed/bioactivity_preprocessed_data.csv
Resolving github.com (github.com)... 140.82.114.4
Connecting to github.com (github.com)|140.82.114.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/Sakhiur2022/QSAR-modeling-for-DHFR-TS/refs/heads/main/data/preprocessed/bioactivity_preprocessed_data.csv [following]
--2026-06-12 18:00:49--  https://raw.githubusercontent.com/Sakhiur2022/QSAR-modeling-for-DHFR-TS/refs/heads/main/data/preprocessed/bioactivity_preprocessed_data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 76537 (75K) [text/plain]
Saving to: ‘bioactivity_preprocessed_data.csv’

bioactivity_preproc 100%[===================>]  74.74K  --.-KB/s    in 0.01s

2026-06-12 18:00:49 (5.49 MB/s) - ‘bioactivity_preprocessed_data.csv’ saved [76537/76537]

In [3]:
import pandas as pd

In [4]:
dataset_preprocessed = pd.read_csv('bioactivity_preprocessed_data.csv')

In [6]:
dataset_preprocessed

,molecule_chembl_id,canonical_smiles,bioactivity_class,standard_value,pChEMBL_value
0,CHEMBL419055,CCc1nc(N)nc(N)c1Cc1cc(OC)c(OC)c(OC)c1,active,4.300,8.37
1,CHEMBL419231,CCCOc1cc(Cc2cnc(N)nc2N)ccc1OC,active,144.400,6.84
2,CHEMBL332013,CCOc1ccc(Cc2cnc(N)nc2N)cc1OC,active,187.400,6.73
3,CHEMBL279948,Cc1nc(N)nc(N)c1Cc1ccc(OCc2ccccc2)c(OCc2ccccc2)c1,active,241.000,6.62
4,CHEMBL325533,COc1cc(Cc2c(C)nc(N)nc2N)cc(OC)c1OC,active,520.300,6.28
...,...,...,...,...,...
1069,CHEMBL422005,Nc1nc(N)c(-c2cccc(Cl)c2)c(CCCO)n1,active,29.000,7.54
1070,CHEMBL422005,Nc1nc(N)c(-c2cccc(Cl)c2)c(CCCO)n1,intermediate,1900.000,5.72
1071,CHEMBL5499545,CCc1nc(N)nc(N)c1Cc1ccc(-c2cccc(C(=O)O)c2)cc1,active,0.290,9.54
1072,CHEMBL5822647,CCCc1nc(N)nc(N)c1N1CCN(c2ccccc2)CC1,active,14.100,7.85
1073,CHEMBL34259,CN(Cc1cnc2nc(N)nc(N)c2n1)c1ccc(C(=O)N[C@@H](CC...,active,0.891,9.05

In [9]:
selection = ['canonical_smiles','molecule_chembl_id']
dataset_preprocessed_selection = dataset_preprocessed[selection]
dataset_preprocessed_selection.to_csv('molecule.smi', sep='\t', index=False, header=False)

In [10]:
! cat molecule.smi | head -5

CCc1nc(N)nc(N)c1Cc1cc(OC)c(OC)c(OC)c1	CHEMBL419055
CCCOc1cc(Cc2cnc(N)nc2N)ccc1OC	CHEMBL419231
CCOc1ccc(Cc2cnc(N)nc2N)cc1OC	CHEMBL332013
Cc1nc(N)nc(N)c1Cc1ccc(OCc2ccccc2)c(OCc2ccccc2)c1	CHEMBL279948
COc1cc(Cc2c(C)nc(N)nc2N)cc(OC)c1OC	CHEMBL325533

In [11]:
! cat molecule.smi | wc -l

1074

## **Calculate fingerprint descriptors**

### **New version using pypadel**

In [12]:
! wget https://github.com/Sakhiur2022/QSAR-modeling-for-DHFR-TS/raw/refs/heads/main/fingerprints_xml.zip

--2026-06-12 18:04:03--  https://github.com/Sakhiur2022/QSAR-modeling-for-DHFR-TS/raw/refs/heads/main/fingerprints_xml.zip
Resolving github.com (github.com)... 140.82.112.3
Connecting to github.com (github.com)|140.82.112.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/Sakhiur2022/QSAR-modeling-for-DHFR-TS/refs/heads/main/fingerprints_xml.zip [following]
--2026-06-12 18:04:03--  https://raw.githubusercontent.com/Sakhiur2022/QSAR-modeling-for-DHFR-TS/refs/heads/main/fingerprints_xml.zip
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10871 (11K) [application/zip]
Saving to: ‘fingerprints_xml.zip’

fingerprints_xml.zi 100%[===================>]  10.62K  --.-KB/s    in 0s

2026-06-12 18:04:03 (88.1 MB/s) - ‘fingerprints_xml.zip’ saved [10871/10871]

In [13]:
! unzip fingerprints_xml.zip

Archive:  fingerprints_xml.zip
  inflating: AtomPairs2DFingerprintCount.xml
  inflating: AtomPairs2DFingerprinter.xml
  inflating: EStateFingerprinter.xml
  inflating: ExtendedFingerprinter.xml
  inflating: Fingerprinter.xml
  inflating: GraphOnlyFingerprinter.xml
  inflating: KlekotaRothFingerprintCount.xml
  inflating: KlekotaRothFingerprinter.xml
  inflating: MACCSFingerprinter.xml
  inflating: PubchemFingerprinter.xml
  inflating: SubstructureFingerprintCount.xml
  inflating: SubstructureFingerprinter.xml

In [16]:
FP_list = ['AtomPairs2DCount',
 'AtomPairs2D',
 'EState',
 'CDKextended',
 'CDK',
 'CDKgraphonly',
 'KlekotaRothCount',
 'KlekotaRoth',
 'MACCS',
 'PubChem',
 'SubstructureCount',
 'Substructure']

In [18]:
import glob
xml_files = glob.glob("*.xml")
xml_files.sort()
xml_files

['AtomPairs2DFingerprintCount.xml',
 'AtomPairs2DFingerprinter.xml',
 'EStateFingerprinter.xml',
 'ExtendedFingerprinter.xml',
 'Fingerprinter.xml',
 'GraphOnlyFingerprinter.xml',
 'KlekotaRothFingerprintCount.xml',
 'KlekotaRothFingerprinter.xml',
 'MACCSFingerprinter.xml',
 'PubchemFingerprinter.xml',
 'SubstructureFingerprintCount.xml',
 'SubstructureFingerprinter.xml']

In [19]:
fp = dict(zip(FP_list, xml_files))
fp

{'AtomPairs2DCount': 'AtomPairs2DFingerprintCount.xml',
 'AtomPairs2D': 'AtomPairs2DFingerprinter.xml',
 'EState': 'EStateFingerprinter.xml',
 'CDKextended': 'ExtendedFingerprinter.xml',
 'CDK': 'Fingerprinter.xml',
 'CDKgraphonly': 'GraphOnlyFingerprinter.xml',
 'KlekotaRothCount': 'KlekotaRothFingerprintCount.xml',
 'KlekotaRoth': 'KlekotaRothFingerprinter.xml',
 'MACCS': 'MACCSFingerprinter.xml',
 'PubChem': 'PubchemFingerprinter.xml',
 'SubstructureCount': 'SubstructureFingerprintCount.xml',
 'Substructure': 'SubstructureFingerprinter.xml'}

In [24]:
from padelpy import padeldescriptor

fingerprint = 'SubstructureCount'

fingerprint_output_file = ''.join([fingerprint,'.csv'])
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='molecule.smi',
                d_file=fingerprint_output_file,
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

## **Display calculated fingerprints**

In [25]:
descriptors=pd.read_csv(fingerprint_output_file)
descriptors

,Name,SubFPC1,SubFPC2,SubFPC3,SubFPC4,SubFPC5,SubFPC6,SubFPC7,SubFPC8,SubFPC9,...,SubFPC298,SubFPC299,SubFPC300,SubFPC301,SubFPC302,SubFPC303,SubFPC304,SubFPC305,SubFPC306,SubFPC307
0,CHEMBL419055,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,9.0,9.0,6.0,0.0,0.0,0.0,0.0,10.0
1,CHEMBL419231,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,8.0,8.0,6.0,0.0,0.0,0.0,0.0,10.0
2,CHEMBL332013,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,7.0,7.0,5.0,0.0,0.0,0.0,0.0,10.0
3,CHEMBL279948,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,9.0,9.0,8.0,0.0,0.0,0.0,0.0,22.0
4,CHEMBL325533,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,8.0,8.0,5.0,0.0,0.0,0.0,0.0,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1069,CHEMBL422005,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,6.0,6.0,3.0,0.0,0.0,0.0,0.0,10.0
1070,CHEMBL422005,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,6.0,6.0,3.0,0.0,0.0,0.0,0.0,10.0
1071,CHEMBL5499545,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,7.0,7.0,4.0,0.0,0.0,0.0,0.0,17.0
1072,CHEMBL5822647,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,11.0,11.0,4.0,0.0,0.0,0.0,0.0,12.0
1073,CHEMBL34259,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,13.0,13.0,10.0,0.0,0.0,0.0,0.0,18.0

## **Preparing the X and Y Data Matrices**

### **X data matrix**

In [ ]:
df3_X = pd.read_csv('descriptors_output.csv')

In [ ]:
df3_X

,Name,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,CHEMBL133897,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,CHEMBL336398,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,CHEMBL131588,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,CHEMBL130628,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,CHEMBL130478,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4690,CHEMBL4293155,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4691,CHEMBL4282558,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4692,CHEMBL4281727,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4693,CHEMBL4292349,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4694,CHEMBL4278260,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
df3_X = df3_X.drop(columns=['Name'])
df3_X

,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,PubchemFP9,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4690,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4691,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4692,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4693,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4694,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

## **Y variable**

### **Convert IC50 to pIC50**

In [ ]:
df3_Y = df3['pIC50']
df3_Y

0       6.124939
1       7.000000
2       4.301030
3       6.522879
4       6.096910
          ...
4690    5.612610
4691    5.595166
4692    5.419075
4693    5.460924
4694    5.555955
Name: pIC50, Length: 4695, dtype: float64

## **Combining X and Y variable**

In [ ]:
dataset3 = pd.concat([df3_X,df3_Y], axis=1)
dataset3

,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,PubchemFP9,...,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880,pIC50
0,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,6.124939
1,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,7.000000
2,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,4.301030
3,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,6.522879
4,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,6.096910
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4690,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,5.612610
4691,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,5.595166
4692,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,5.419075
4693,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,5.460924
4694,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,5.555955

In [ ]:
dataset3.to_csv('acetylcholinesterase_06_bioactivity_data_3class_pIC50_pubchem_fp.csv', index=False)

# **Let's download the CSV file to your local computer for the Part 3B (Model Building).**