<a href="https://colab.research.google.com/github/Sakhiur2022/QSAR-modeling-for-DHFR-TS/blob/main/notebooks/bioactivity_data_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Importing libraries**

In [3]:
# Import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Load Dataset

In [1]:
! wget https://github.com/Sakhiur2022/QSAR-modeling-for-DHFR-TS/raw/refs/heads/main/data/raw/CHEMBL1939.csv

--2026-06-11 07:45:17--  https://github.com/Sakhiur2022/QSAR-modeling-for-DHFR-TS/raw/refs/heads/main/data/CHEMBL1939.csv
Resolving github.com (github.com)... 20.27.177.113
Connecting to github.com (github.com)|20.27.177.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/Sakhiur2022/QSAR-modeling-for-DHFR-TS/refs/heads/main/data/CHEMBL1939.csv [following]
--2026-06-11 07:45:18--  https://raw.githubusercontent.com/Sakhiur2022/QSAR-modeling-for-DHFR-TS/refs/heads/main/data/CHEMBL1939.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1122750 (1.1M) [text/plain]
Saving to: ‘CHEMBL1939.csv’

CHEMBL1939.csv      100%[===================>]   1.07M  7.11MB/s    in 0.2s

2026-06-11 07:45:18 (7.11 MB/s) - ‘CHEMBL1939.csv’ saved [1122750/1122750]

In [5]:
dataset = pd.read_csv('CHEMBL1939.csv',sep=";")
dataset

,Molecule ChEMBL ID,Molecule Name,Molecule Max Phase,Molecular Weight,#RO5 Violations,AlogP,Compound Key,Smiles,Standard Type,Standard Relation,...,Document ChEMBL ID,Source ID,Source Description,Document Journal,Document Year,Cell ChEMBL ID,Properties,Action Type,Standard Text Value,Value
0,CHEMBL22,TRIMETHOPRIM,4.0,290.32,0,1.26,TRIMETHOPRIME,COc1cc(Cc2cnc(N)nc2N)cc(OC)c1OC,Relative activity,'=',...,CHEMBL1148379,1,Scientific Literature,J Med Chem,2004,NaN,NaN,NaN,NaN,1.000
1,CHEMBL22,TRIMETHOPRIM,4.0,290.32,0,1.26,TRIMETHOPRIME,COc1cc(Cc2cnc(N)nc2N)cc(OC)c1OC,Relative activity,'=',...,CHEMBL1148379,1,Scientific Literature,J Med Chem,2004,NaN,NaN,NaN,NaN,1.000
2,CHEMBL419055,NaN,NaN,318.38,0,1.82,52,CCc1nc(N)nc(N)c1Cc1cc(OC)c(OC)c(OC)c1,Ki,'=',...,CHEMBL1148379,1,Scientific Literature,J Med Chem,2004,NaN,NaN,NaN,NaN,4.300
3,CHEMBL419055,NaN,NaN,318.38,0,1.82,52,CCc1nc(N)nc(N)c1Cc1cc(OC)c(OC)c(OC)c1,IC50,'>',...,CHEMBL1148379,1,Scientific Literature,J Med Chem,2004,NaN,NaN,NaN,NaN,0.370
4,CHEMBL419231,NaN,NaN,288.35,0,2.03,23,CCCOc1cc(Cc2cnc(N)nc2N)ccc1OC,Ki,'=',...,CHEMBL1148379,1,Scientific Literature,J Med Chem,2004,NaN,NaN,NaN,NaN,144.400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1899,CHEMBL5822647,NaN,NaN,312.42,0,1.92,BDBM585306,CCCc1nc(N)nc(N)c1N1CCN(c2ccccc2)CC1,kon,'=',...,CHEMBL5729483,37,BindingDB Patent Bioactivity Data,NaN,2022,NaN,NaN,NaN,NaN,NaN
1900,CHEMBL34259,METHOTREXATE,4.0,454.45,0,0.27,BDBM66082,CN(Cc1cnc2nc(N)nc(N)c2n1)c1ccc(C(=O)N[C@@H](CC...,k_off,'=',...,CHEMBL5729483,37,BindingDB Patent Bioactivity Data,NaN,2022,NaN,NaN,NaN,NaN,NaN
1901,CHEMBL36,PYRIMETHAMINE,4.0,248.72,0,2.52,BDBM18512,CCc1nc(N)nc(N)c1-c1ccc(Cl)cc1,k_off,'=',...,CHEMBL5729483,37,BindingDB Patent Bioactivity Data,NaN,2022,NaN,NaN,NaN,NaN,NaN
1902,CHEMBL34259,METHOTREXATE,4.0,454.45,0,0.27,BDBM66082,CN(Cc1cnc2nc(N)nc(N)c2n1)c1ccc(C(=O)N[C@@H](CC...,IC50,'=',...,CHEMBL5729483,37,BindingDB Patent Bioactivity Data,NaN,2022,NaN,NaN,NaN,NaN,0.891
1903,CHEMBL3913021,NaN,NaN,199.21,0,2.45,"Table 2, R8C5",O=C(O)c1cccc(-c2ccncc2)c1,Ki,'>',...,CHEMBL6096693,1,Scientific Literature,J Med Chem,2025,NaN,NaN,NaN,NaN,500.000

In [8]:
dataset.columns

Index(['Molecule ChEMBL ID', 'Molecule Name', 'Molecule Max Phase',
       'Molecular Weight', '#RO5 Violations', 'AlogP', 'Compound Key',
       'Smiles', 'Standard Type', 'Standard Relation', 'Standard Value',
       'Standard Units', 'pChEMBL Value', 'Data Validity Comment', 'Comment',
       'Uo Units', 'Ligand Efficiency BEI', 'Ligand Efficiency LE',
       'Ligand Efficiency LLE', 'Ligand Efficiency SEI', 'Potential Duplicate',
       'Assay ChEMBL ID', 'Assay Description', 'Assay Type', 'BAO Format ID',
       'BAO Label', 'Assay Organism', 'Assay Tissue ChEMBL ID',
       'Assay Tissue Name', 'Assay Cell Type', 'Assay Subcellular Fraction',
       'Assay Parameters', 'Assay Variant Accession', 'Assay Variant Mutation',
       'Target ChEMBL ID', 'Target Name', 'Target Organism', 'Target Type',
       'Document ChEMBL ID', 'Source ID', 'Source Description',
       'Document Journal', 'Document Year', 'Cell ChEMBL ID', 'Properties',
       'Action Type', 'Standard Text Value', 'Value'],
      dtype='object')

## **Handling missing data**
If any compounds has missing value for the **standard_value** column then drop it

In [26]:
dataset_cleaned = dataset[dataset['pChEMBL Value'].notna()]

## **Data pre-processing of the bioactivity data**

### **Labeling compounds as either being active, inactive or intermediate**
The bioactivity data is in the pChEMBL unit. Compounds having values of less than 1000 nM will be considered to be **active** while those greater than 10,000 nM will be considered to be **inactive**. As for those values in between 1,000 and 10,000 nM will be referred to as **intermediate**.

In [27]:
bioactivity_class = []
for i in dataset_cleaned['Standard Value']:
  if float(i) >= 10000:
    bioactivity_class.append("inactive")
  elif float(i) <= 1000:
    bioactivity_class.append("active")
  else:
    bioactivity_class.append("intermediate")

### **Iterate the *molecule_chembl_id* to a list**

In [30]:
mol_cid = []
for i in dataset_cleaned['Molecule ChEMBL ID']:
  mol_cid.append(i)

### **Iterate *canonical_smiles* to a list**

In [32]:
canonical_smiles = []
for i in dataset_cleaned['Smiles']:
  canonical_smiles.append(i)

### **Iterate *standard_value* to a list**

In [34]:
standard_value = []
for i in dataset_cleaned['Standard Value']:
  standard_value.append(i)

### **Iterate pChEMBL Value to a list**

In [40]:
pChEMBL_value = []
for i in dataset_cleaned['pChEMBL Value']:
  pChEMBL_value.append(i)

### **Combine the 4 lists into a dataframe**

In [41]:
data_tuples = list(zip(mol_cid, canonical_smiles, bioactivity_class, standard_value, pChEMBL_value))
dataset_preprocessed = pd.DataFrame( data_tuples,  columns=['molecule_chembl_id', 'canonical_smiles', 'bioactivity_class', 'standard_value','pChEMBL_value'])

In [42]:
dataset_preprocessed

,molecule_chembl_id,canonical_smiles,bioactivity_class,standard_value,pChEMBL_value
0,CHEMBL419055,CCc1nc(N)nc(N)c1Cc1cc(OC)c(OC)c(OC)c1,active,4.300,8.37
1,CHEMBL419231,CCCOc1cc(Cc2cnc(N)nc2N)ccc1OC,active,144.400,6.84
2,CHEMBL332013,CCOc1ccc(Cc2cnc(N)nc2N)cc1OC,active,187.400,6.73
3,CHEMBL279948,Cc1nc(N)nc(N)c1Cc1ccc(OCc2ccccc2)c(OCc2ccccc2)c1,active,241.000,6.62
4,CHEMBL325533,COc1cc(Cc2c(C)nc(N)nc2N)cc(OC)c1OC,active,520.300,6.28
...,...,...,...,...,...
1069,CHEMBL422005,Nc1nc(N)c(-c2cccc(Cl)c2)c(CCCO)n1,active,29.000,7.54
1070,CHEMBL422005,Nc1nc(N)c(-c2cccc(Cl)c2)c(CCCO)n1,intermediate,1900.000,5.72
1071,CHEMBL5499545,CCc1nc(N)nc(N)c1Cc1ccc(-c2cccc(C(=O)O)c2)cc1,active,0.290,9.54
1072,CHEMBL5822647,CCCc1nc(N)nc(N)c1N1CCN(c2ccccc2)CC1,active,14.100,7.85
1073,CHEMBL34259,CN(Cc1cnc2nc(N)nc(N)c2n1)c1ccc(C(=O)N[C@@H](CC...,active,0.891,9.05

Saves dataframe to CSV file

In [43]:
 dataset_preprocessed.to_csv('bioactivity_preprocessed_data.csv', index=False)

In [44]:
! ls -l

total 1180
-rw-r--r-- 1 root root   76537 Jun 11 08:26 bioactivity_preprocessed_data.csv
-rw-r--r-- 1 root root 1122750 Jun 11 07:45 CHEMBL1939.csv
drwxr-xr-x 1 root root    4096 Jun  4 13:32 sample_data

---